name: 'Create Version'
description: 'Create version number for Android'
inputs:
  versionNumber:  # id of input
    description: 'Current version number'
    required: true
    default: '1.0.0'
  platform:  # id of input
    description: 'Platfrom input'
    required: true
    default: 'android'
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  commitMessage:  # id of input
    description: 'Commit message '
    required: true
    default: 'message'
  configuration:  # id of input
    description: 'Configuration selected '
    required: false
    default: 'some message'  
  numberVersion:  # id of input
    description: 'number of verion build app'
    required: false
  aplication:  # id of input
    description: 'name aplication'
    required: true
  typeEnvironment:  # id of input
    description: 'environment build app'	
    required: false
    
    
outputs:
  new-version-number: # id of output
    description: 'The new version number' 
  assemble_value: # id of output
    description: 'value for assemble'
  final_path_apk: # id of output
    description: 'final path apk'
  new-version-code: # id of output
    description: 'The new version code'
  qa-version-number: # id of output
    description: 'The version code in ()'
    
runs:
  using: 'node16'
  main: 'index.js'
